### ISSUE TITLE
What need to be persistent for docker?

### ISSUE THREAD

**Issue by xianx** [playsms/docker-playsms#3]
For docker it need some persistent like logs, config files and other location so that it wont get vanish on docker restart. I have found no documentation on what need to be persistent. Where can I find it?  Or please describe for docker what, which directory or file need to be persistent?

**Comment by antonraharja** [comment]
please discuss this on forum, https://forum.playsms.org

**Comment by xianx** [comment]
I think ihis information need to be documented on this repository so that developer can setup docker correctly and not a forum discussion.

**Comment by GabinhoJean** [comment]
I have exactly the same problem.

there is any updated informations ?
