### ISSUE TITLE
How to check which version of playSMS is running?

### ISSUE THREAD

**Issue by xianx** [playsms/docker-playsms#4]
How to check which version of playSMS is running?

**Comment by antonraharja** [comment]
```
playsmsd check
```

from inside the container, use `docker exec`

**Comment by xianx** [comment]
# playsmsd check
PLAYSMSD_CONF = /etc/playsmsd.conf
PLAYSMS_PATH = /var/www/html
PLAYSMS_LIB = /var/lib/playsms
PLAYSMS_BIN = /usr/local/bin
PLAYSMS_LOG = /var/log/playsms
DAEMON_SLEEP = 1
ERROR_REPORTING = E_ALL ^ (E_NOTICE | E_WARNING)
IS_RUNNING = 1
PIDS schedule = 2211
PIDS ratesmsd = 2213
PIDS dlrssmsd = 2215
PIDS recvsmsd = 2217
PIDS sendsmsd = 2220

No version info.
