### ISSUE TITLE
Using separate docker instance of database with playsmsm docker

### ISSUE THREAD

**Issue by xianx** [playsms/docker-playsms#5]
The docker image of playsms is not persistent. As the database (mysql) is inside docker, the database is not persistent. All database data gone after playsms docker instance restarted or host restarted.

I am trying to use a separate mysql docker instance and trying to connect it to playsms docker instance. But even with correct value on config.php in playsms it shows "database connection error message"

How to use a separate docker instance of database with playsms docker?

**Comment by antonraharja** [comment]
please continue in https://forum.playsms.org
