### ISSUE TITLE
Example ssh to the docker port should be 2222 instead of ssh -p 11022 root@localhost

### ISSUE THREAD

**Issue by azaman2204** [playsms/docker-playsms#7]
ssh to the docker port should be 2222 instead of ssh -p 11022 root@localhost
since the example running the docker image for ssh is set to 2222

**Comment by antonraharja** [comment]
see readme, see the docker run command, the -p param is the port, -p 2222:22 means map port 2222 to port 22 inside docker

please continue in forum.playsms.org
